### ISSUE TITLE
Systray icon not visible on plasma and gnome

### ISSUE THREAD

**Issue by andrevmatos** [flathub/org.quassel_irc.QuasselClient#1]
Maybe some issue with libappindicator, or alike, but at least both on Gnome and Plasma (current), quassel on flatpak (updated) does not show it's systray icon, making it impossible to restore if minimized. If done, one needs to update it's config file manually to make it show again. Telegram Desktop (not sure if based on same runtime, but it's another Qt app) shows systray icon correctly.

**Comment by TingPing** [comment]
A starting point is adding `--talk-name=org.kde.StatusNotifierWatcher` but that alone doesn't do it here on GNOME. I'm not super familiar with Qt so not sure what else is missing. @grulja any idea?

**Comment by benwaffle** [comment]
FYI - it works for me on GNOME. Maybe its not an issue with this flatpak?

@andrevmatos if you're using GNOME 3.26, make sure you have TopIcons or TopIcons Plus installed

**Comment by TingPing** [comment]
Oh I assumed it was using StatusNotifier since that is built into Qt I believe.

**Comment by grulja** [comment]
It seems to be using StatusNotifier, but some older version copied from KDE some time ago. We changed StatusNotifier implementation in KDE not to register org.kde.StatusNotifierItem-x-y for each app but register app service name in org.kde.StatusNotifierWatcher instead, see [1]. Quassel seems to register org.kde.StatusNotifierItem-x-y, but my guess is that this is not taken into account by our implementation.

[1] - https://cgit.kde.org/knotifications.git/commit/?id=2b0b904ee0e986ea0a96a8f54e1522e492885ffe

**Comment by grulja** [comment]
Ok, it is registered correctly, but given it uses its own implementation you have to use:
`flatpak run--own-name=org.kde.StatusNotifierItem-2-1 --talk-name=org.kde.StatusNotifierWatcher org.quassel_irc.QuasselClient`

**Comment by andrevmatos** [comment]
@grulja Running your command-line didn't work here, quassel still lacks systray icon.

**Comment by oponcea** [comment]
ovidiu@server:~$ quassel --talk-name=org.kde.StatusNotifierWatcher
Unknown option 'talk-name'.

It doesn't work for me either. What else can we try? Thanks!

**Comment by benwaffle** [comment]
@oponcea that is a flatpak argument, not a quassel argument
